server:
  port: 8081
#spring:
#  datasource:
##    dynamic:
##      primary: sat #设置默认的数据源或者数据源组,默认值即为mysql1
##      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
##      datasource:
##        sat:
#        driver-class-name: org.sqlite.JDBC
#        url: jdbc:sqlite::resource:db/leoa.db
#        hostinfo:
#          url: jdbc:mysql://localhost:3306/hostinfo
#          username: root
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: tb_
#      id-type: auto
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:db/leoa.db

